[package]
name = "github_client"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
thiserror = "1.0"
derive_more = "0.99"
clients = { path = "../../clients" }
reqwest = { version = "0.11", features = ["json"] }
secrecy = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
paginate = "1.1"

[dev-dependencies]
tokio = { version = "1.18", features = ["macros", "test-util"] }
tokio-test = "0.4"
