[package]
name = "bus_factor"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
clients = { path = "../clients" }
github_client = { path = "../clients/github" }
tokio = { version = "1.18", features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream = { version = "0.1", features = ["tokio-util"] }
futures = { version = "0.3", features = ["std"] }
log = "0.4"
derive-new = "0.5"
