[package]
name = "bus_factor"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
derive_more = { version = "0.99", features = ["from"] }
derive-new = "0.5"
futures = { version = "0.3", features = ["std"] }
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.18", features = ["macros", "rt-multi-thread", "sync"] }
async-trait = "0.1"
reqwest = "0.11"
anyhow = "1.0"
url = "2.2"
