on:
  release:
    types: [created]

name: Release

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]
    steps:
      - uses: actions/checkout@master
      - name: Release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
